/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.AgendaController;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JTable;

/**
 *
 * @author DIEGO
 */
public class Agenda extends javax.swing.JFrame {

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() throws SQLException, ParseException {
        initComponents();
        controller = new AgendaController(this);
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        lblCliente = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        lblValor = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jComboBox_Cliente = new javax.swing.JComboBox<>();
        txtData = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabelCadastro_servico = new javax.swing.JLabel();
        jComboBox_Servico = new javax.swing.JComboBox<>();
        txtObservacao = new javax.swing.JTextField();
        lblServico = new javax.swing.JLabel();
        btAgendar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        jLabelCadastro_sombra = new javax.swing.JLabel();
        jLabelBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblID.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID");
        lblID.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 60, 30));

        txtID.setBackground(new java.awt.Color(255, 255, 255));
        txtID.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtID.setForeground(new java.awt.Color(56, 105, 138));
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 310, 35));

        lblCliente.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setText("Cliente");
        lblCliente.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(lblCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 60, 30));

        txtValor.setBackground(new java.awt.Color(255, 255, 255));
        txtValor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtValor.setForeground(new java.awt.Color(56, 105, 138));
        getContentPane().add(txtValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 310, 35));

        lblValor.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblValor.setForeground(new java.awt.Color(255, 255, 255));
        lblValor.setText("Valor");
        lblValor.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 60, 30));

        lblData.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblData.setForeground(new java.awt.Color(255, 255, 255));
        lblData.setText("Data");
        lblData.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(lblData, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 60, 30));

        jComboBox_Cliente.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Cliente.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Cliente.setForeground(new java.awt.Color(56, 105, 138));
        jComboBox_Cliente.setBorder(null);
        jComboBox_Cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox_Cliente.setOpaque(false);
        getContentPane().add(jComboBox_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 310, 35));

        txtData.setBackground(new java.awt.Color(255, 255, 255));
        txtData.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtData.setForeground(new java.awt.Color(56, 105, 138));
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 310, 35));

        lblHora.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setText("Hora");
        lblHora.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 60, 30));

        txtHora.setBackground(new java.awt.Color(255, 255, 255));
        txtHora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtHora.setForeground(new java.awt.Color(56, 105, 138));
        getContentPane().add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 610, 310, 35));

        jLabelCadastro_servico.setFont(new java.awt.Font("Lato", 1, 18)); // NOI18N
        jLabelCadastro_servico.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCadastro_servico.setText("Agenda");
        jLabelCadastro_servico.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(jLabelCadastro_servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, 110, 50));

        jComboBox_Servico.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Servico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jComboBox_Servico.setForeground(new java.awt.Color(56, 105, 138));
        jComboBox_Servico.setBorder(null);
        jComboBox_Servico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox_Servico.setOpaque(false);
        getContentPane().add(jComboBox_Servico, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 310, 35));

        txtObservacao.setBackground(new java.awt.Color(255, 255, 255));
        txtObservacao.setForeground(new java.awt.Color(56, 105, 138));
        txtObservacao.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        getContentPane().add(txtObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 520, 320));

        lblServico.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        lblServico.setForeground(new java.awt.Color(255, 255, 255));
        lblServico.setText("Serviço");
        lblServico.setMaximumSize(new java.awt.Dimension(50, 25));
        getContentPane().add(lblServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 60, 30));

        btAgendar.setBackground(new java.awt.Color(56, 105, 138));
        btAgendar.setForeground(new java.awt.Color(255, 255, 255));
        btAgendar.setText("Agendar");
        btAgendar.setBorder(null);
        getContentPane().add(btAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 610, 520, 35));

        TableAgendamentos.setBackground(new java.awt.Color(255, 255, 255));
        TableAgendamentos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TableAgendamentos.setForeground(new java.awt.Color(56, 105, 138));
        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Serviço", "Valor", "Data", "Hora"
            }
        ));
        jScrollPane1.setViewportView(TableAgendamentos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 690, 950, 210));

        jLabelCadastro_sombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(jLabelCadastro_sombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, -1));

        jLabelBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(jLabelBG, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Agenda().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JButton btAgendar;
    private javax.swing.JComboBox<String> jComboBox_Cliente;
    private javax.swing.JComboBox<String> jComboBox_Servico;
    private javax.swing.JLabel jLabelBG;
    private javax.swing.JLabel jLabelCadastro_servico;
    private javax.swing.JLabel jLabelCadastro_sombra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblServico;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtObservacao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables

    private void iniciar() throws SQLException, ParseException {
        this.controller.atualizaTabela();
        this.controller.atualizaCliente();
        this.controller.atualizaServico();
    }

    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }

    public JComboBox<String> getjComboBox_Cliente() {
        return jComboBox_Cliente;
    }

    public void setjComboBox_Cliente(JComboBox<String> jComboBox_Cliente) {
        this.jComboBox_Cliente = jComboBox_Cliente;
    }

    public JComboBox<String> getjComboBox_Servico() {
        return jComboBox_Servico;
    }

    public void setjComboBox_Servico(JComboBox<String> jComboBox_Servico) {
        this.jComboBox_Servico = jComboBox_Servico;
    }

    
    
    
    
    
    
    
    
}
