/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MenuPrincipalController;
import Model.Agendamento;
import Model.Cliente;
import Model.Servico;
import Model.Usuario;
import dao.AgendamentoDAO;
import dao.Conexao;
import dao.UsuarioDAO;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DIEGO
 */
public class MenuPrincipal extends javax.swing.JFrame {

    private final MenuPrincipalController controller;
    private Object telaDeUsuarios;

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.controller = new MenuPrincipalController(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuUsuario = new javax.swing.JMenuItem();
        jMenuServico = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuOperacao = new javax.swing.JMenu();
        jMenuOperacaoAgenda = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1300, 1000));
        setMinimumSize(new java.awt.Dimension(1300, 1000));
        setPreferredSize(new java.awt.Dimension(1300, 1000));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/MenuFundo2.png"))); // NOI18N

        jMenuCadastro.setText("Cadastro");

        jMenuUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/usuario-icon.png"))); // NOI18N
        jMenuUsuario.setText("Usuário");
        jMenuUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuUsuarioActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuUsuario);

        jMenuServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/tesoura-icon.png"))); // NOI18N
        jMenuServico.setText("Serviço");
        jMenuServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuServicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuServico);

        jMenuCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/cliente-icon.png"))); // NOI18N
        jMenuCliente.setText("Cliente");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuCliente);

        jMenuBar1.add(jMenuCadastro);

        jMenuOperacao.setText("Operação");

        jMenuOperacaoAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/icons/agenda-icon.png"))); // NOI18N
        jMenuOperacaoAgenda.setText("Agenda");
        jMenuOperacaoAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuOperacaoAgendaActionPerformed(evt);
            }
        });
        jMenuOperacao.add(jMenuOperacaoAgenda);

        jMenuBar1.add(jMenuOperacao);

        jMenuRelatorio.setText("Relatório");
        jMenuBar1.add(jMenuRelatorio);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuOperacaoAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuOperacaoAgendaActionPerformed
        try {
            try {
                this.controller.navegarParaAgenda();
            } catch (ParseException ex) {
                Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
            Connection conexao = new Conexao().getConnection();            
            AgendamentoDAO agendamentoDao = new AgendamentoDAO(conexao);
            
            // Agendar
            //Teste insert
            //Agendamento agendamentoInsert = new Agendamento(cliente, servico, 10f, "16/11/2021");
            //Agendamento agendamentoInserido = agendamentoDao.insert(agendamentoInsert);
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuOperacaoAgendaActionPerformed

    private void jMenuUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuUsuarioActionPerformed

            
            
        try {
            MenuUsuario telaDeUsuarios = new MenuUsuario();
            telaDeUsuarios.setVisible(true);
            Connection conexao = new Conexao().getConnection();            
            UsuarioDAO usuarioDao = new UsuarioDAO(conexao);
            
            //Teste insert
            Usuario usuarioInsert = new Usuario("testeUsuarioInsert", "654321");
            Usuario usuarioInserido = usuarioDao.insert(usuarioInsert);
            
            //Teste select por ID
            Usuario usuarioSelecionado = usuarioDao.selectPorId(usuarioInserido);
            //erro ao encontrar a variável usuarioSelecionado
            
            //Teste delete
            usuarioDao.delete(usuarioSelecionado);//erro
            
            //Teste select all
            ArrayList<Usuario> usuarios = usuarioDao.selectAll();
            
            for(Usuario usuario : usuarios){
                //System.out.println(usuario.getNome());
                System.out.println(usuario.getUsuario());
            };
            
            
        } catch (SQLException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jMenuUsuarioActionPerformed

    private void jMenuServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuServicoActionPerformed
        FormCadastroServico telaCadastro = new FormCadastroServico();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_jMenuServicoActionPerformed

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        FormCadastroCliente telaCadastroCliente = new FormCadastroCliente();
        telaCadastroCliente.setVisible(true);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenu jMenuOperacao;
    private javax.swing.JMenuItem jMenuOperacaoAgenda;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenuItem jMenuServico;
    private javax.swing.JMenuItem jMenuUsuario;
    // End of variables declaration//GEN-END:variables
}
